### ISSUE TITLE
webui error

### ISSUE THREAD

**Issue by fengjian1993** [fieldryand/goflow#85]
pull "main" branch 
run "rpm install" and "npm run build".
run goflow-example.go main
go to http://127.0.0.1:8181/ui/jobs/example-complex-analytics and can't see whole flow svg in page.
see web console shows error:

dist.js:2  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'transform')
    at SVGSVGElement.<anonymous> (dist.js:2:629443)
    at En.call (dist.js:2:377363)
    at M.emit (dist.js:2:627082)
    at M.zoom (dist.js:2:626924)
    at SVGSVGElement.<anonymous> (dist.js:2:625500)
    at Le.each (dist.js:2:387189)
    at y.transform (dist.js:2:625448)
    at Le.call (dist.js:2:386770)
    at Module.i (dist.js:2:629489)

how can i fix it ?

**Comment by fieldryand** [comment]
I'm afraid I can't reproduce this issue. Does it happen consistently? What if you refresh the page?
